// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/trade-copilot-p1/Dashboard.tsx": () => import("../components/mockups/trade-copilot-p1/Dashboard.tsx"),
  "./components/mockups/trade-copilot-p1/Login.tsx": () => import("../components/mockups/trade-copilot-p1/Login.tsx"),
  "./components/mockups/trade-copilot-p2/Connections.tsx": () => import("../components/mockups/trade-copilot-p2/Connections.tsx"),
  "./components/mockups/trade-copilot-p2/SyncStatus.tsx": () => import("../components/mockups/trade-copilot-p2/SyncStatus.tsx"),
  "./components/mockups/trade-copilot-p2/TradesList.tsx": () => import("../components/mockups/trade-copilot-p2/TradesList.tsx"),
  "./components/mockups/trade-copilot-p4/JournalLog.tsx": () => import("../components/mockups/trade-copilot-p4/JournalLog.tsx"),
  "./components/mockups/trade-copilot-p4/TagManagement.tsx": () => import("../components/mockups/trade-copilot-p4/TagManagement.tsx"),
  "./components/mockups/trade-copilot-p4/TradeDetail.tsx": () => import("../components/mockups/trade-copilot-p4/TradeDetail.tsx"),
  "./components/mockups/trade-copilot-p3/EquityCurve.tsx": () => import("../components/mockups/trade-copilot-p3/EquityCurve.tsx"),
  "./components/mockups/trade-copilot-p3/SetupPerformance.tsx": () => import("../components/mockups/trade-copilot-p3/SetupPerformance.tsx"),
  "./components/mockups/trade-copilot-p3/TimeAnalysis.tsx": () => import("../components/mockups/trade-copilot-p3/TimeAnalysis.tsx"),
  "./components/mockups/trade-copilot-p6/MultiBroker.tsx": () => import("../components/mockups/trade-copilot-p6/MultiBroker.tsx"),
  "./components/mockups/trade-copilot-p6/PortfolioOverview.tsx": () => import("../components/mockups/trade-copilot-p6/PortfolioOverview.tsx"),
  "./components/mockups/trade-copilot-p6/SyncOrchestration.tsx": () => import("../components/mockups/trade-copilot-p6/SyncOrchestration.tsx"),
  "./components/mockups/trade-copilot-p5/CoachingAlerts.tsx": () => import("../components/mockups/trade-copilot-p5/CoachingAlerts.tsx"),
  "./components/mockups/trade-copilot-p5/StrategyDrift.tsx": () => import("../components/mockups/trade-copilot-p5/StrategyDrift.tsx"),
  "./components/mockups/trade-copilot-p5/WeeklyReview.tsx": () => import("../components/mockups/trade-copilot-p5/WeeklyReview.tsx")
};
